### ISSUE TITLE
client crash when holding BetterBuildersWand

### ISSUE THREAD

**Issue by Seyeght** [pkmnfrk/equivalentintegrations#31]
This crashed the client and not the server
Pack is PO3 v.3.0.40

Crash report https://pastebin.com/vvtpWukT
this happened with the wand already in inventory hotbar, and the player just scrolled to equip it. 

I have also posted it to their git, but posting it here since your mod is referenced.c

**Comment by pkmnfrk** [comment]
Sorry for the delay, it's been a busy few weeks. 

I believe this is probably related to my mod. Let me take a look.

**Comment by pkmnfrk** [comment]
This is fixed in v0.4.3

**Comment by Elmegaard** [comment]
@pkmnfrk This is still an issue for me in v0.4.3

https://pastebin.com/d46qrYeG

I should note, this only happens when you look at a block. I looked at cobblestone and it happened.

**Comment by pkmnfrk** [comment]
Hm, that is a very interesting stack trace. It is, technically, a different issue, but I can track it here.

**Comment by pkmnfrk** [comment]
Actually, I take it back, this is a sufficiently separate issue that I'm going to open a separate ticket

**Comment by pkmnfrk** [comment]
@Elmegaard FYI ⬆️

**Comment by pkmnfrk** [comment]
FYI, the resolution to the other issue is to upgrade ProjectE to 1.4.1, which is the new minimum version

**Comment by Elmegaard** [comment]
Thank you for the very quick reply. I will try it.
